"""add screening status history

Revision ID: 1cc320f00e1c
Revises: 4e12305ce03d
Create Date: 2026-10-05 11:47:25.866883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc320f00e1c'
down_revision: Union[str, Sequence[str], None] = '4e12305ce03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_status_history')
    # ### end Alembic commands ###
